#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = "plotly_white"


# In[34]:


data=pd.read_csv('C:/Users/shrishailbn/Desktop/PYTHON_WORK/supplychain/supply_chain_data.csv')
data.head()


# In[5]:


print(data.info())


# In[6]:


data.describe()


# In[9]:


fig=px.scatter(data,x='Price',y='Revenue generated',color='Product type',hover_data=['Number of products sold'],trendline='ols')
fig.show()


# In[15]:


sales_data=data.groupby('Product type')['Number of products sold'].sum().reset_index()
sales_data


# In[19]:


pie_chart=px.pie(sales_data,values='Number of products sold',names='Product type',
                title='Sales by product type',hover_data=['Number of products sold'],
                hole=0.5,color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()


# In[38]:


total_revenue=data.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig=go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                    y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping Carriers',
                 xaxis_title='Shipping Carriers',
                 yaxis_title='Revenue Generated')
fig.show()


# In[35]:


total_revenue


# In[42]:


avg_time=data.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_cost=data.groupby('Product type')['Manufacturing costs'].mean().reset_index()
result=pd.merge(avg_time,avg_manufacturing_cost,on='Product type')
result.rename(columns={'Lead time': 'Average Lead Time', 'Manufacturing costs': 'Average Manufacturing Costs'},inplace=True)
print(result)


# In[43]:


revenue_chart=px.line(data,x='SKU',y='Revenue generated',title='Revenue Generated by SKU')
revenue_chart.show()


# In[44]:


stock_chart=px.line(data,x='SKU',y='Stock levels',title='Stock Levels by SKU')
stock_chart.show()


# In[45]:


order_quantity_chart=px.bar(data,x='SKU',y='Order quantities',title='Order Quantity by SKU')
order_quantity_chart.show()


# In[46]:


shipping_cost_chart=px.bar(data, x='Shipping carriers', y='Shipping costs',
                          title='Shippoing costs by carriers')
shipping_cost_chart.show()


# In[47]:


transportation_chart=px.pie(data,values='Costs',names='Transportation modes',title='Cost Distribution by Transportation',
                           hole=0.5,color_discrete_sequence=px.colors.qualitative.Pastel)
transportation_chart.show()


# In[48]:


defect_rates_by_product=data.groupby('Product type')['Defect rates'].mean().reset_index()
fig=px.bar(defect_rates_by_product,x='Product type',y='Defect rates',
          title='Average Defect Rates by Product Type')
fig.show()


# In[50]:


pivot_table=pd.pivot_table(data,values='Defect rates',index=['Transportation modes'],aggfunc='mean')
transportation_chart=px.pie(values=pivot_table['Defect rates'],names=pivot_table.index,
                           title='Defecrt rates by transportation modes',
                           hole=0.5,
                           color_discrete_sequence=px.colors.qualitative.Pastel)
transportation_chart.show()


# In[ ]:




